encoding: utf-8
source: "source"
url: "" # the base hostname & protocol for your site, e.g. http://example.com
#logo: "/assets/img/logo.png" 
title: "Российский экспорт + КППК"
# email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Комплексные программы повышения конкурентоспособности:  
  предприятия получат возможность поддержки из федерального бюджета 
  и возьмут на себя обязательства по увеличению экспорта своей продукции.
show_downloads: false
theme: jekyll-theme-minimal