# appveyor.yml

install:
  - set PATH=C:\Ruby23\bin;%PATH%
  - bundle install
  # - gem install jekyll

build: off

before_test:
  - ruby -v
  - gem -v
  - bundle -v
  # more infor
  - jekyll --version
  - gem env
  - bundle info jekyll --path   

test_script:
  - bundle exec jekyll build